apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: grafana-loadbalancer
    protocol: TCP
    port: 3000
    targetPort: http-web-svc
